### ISSUE TITLE
ignition issue with worker node

### ISSUE THREAD

**Issue by paetzoldthomas** [cragr/okd4_files#3]
Hi,
after successful install of masters, I stuck when installing the workers in the moment after 1st reboot (as shown in picture). nslookup can resolve api-int.... well.  
what could be the reason for the get-error? as it's using https - how are certs defined?
any hint would be welcomed on how to go on with worker install.
Thx.

![issue-worker](https://user-images.githubusercontent.com/29278443/80200719-5702cc80-8623-11ea-848c-8aa365f14fff.png)

**Comment by cragr** [comment]
Double check your IPs on the worker nodes, ensure they are pulling the correct IPs and are ping-able.  Also double check HAProxy config and ensure the IPs and ports are correctly defined in there as well.  The certs are automated.  If you are still having issues after double checking, you contact me on the k8s slack channel.

**Comment by cragr** [comment]
Worked with paetzoldthomas on slack and the issue was resolved.
